---
# Source: sssd-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sssd-config
data:
  SSSD_CONF: |
    [sssd]
    #debug_level = 9
    config_file_version = 2
    services = nss,pam
    sbus_timeout = 30
    domains = <mydomain.com>

    [pam]
    #debug_level = 9

    [domain/mydomain.com]
    #debug_level = 9
    enumerate = true
    cache_credentials = true
    ignore_group_members = true
    id_provider = ldap
    auth_provider = ldap
    chpass_provider = ldap
    ldap_uri = ldap://ldap-svc.openldap.svc.cluster.local:389
    ldap_schema = rfc2307bis
    ldap_user_object_class = inetOrgPerson
    ldap_user_member_of = memberof
    ldap_referrals = false
    ldap_search_base = dc=mydomain,dc=com
    ldap_group_search_base = ou=groups,dc=mydomain,dc=com
    ldap_user_search_base = ou=people,dc=mydomain,dc=com
    ldap_default_bind_dn = cn=admin,dc=mydomain,dc=com
    ldap_default_authtok = <Auth Token Value>
    ldap_auth_disable_tls_never_use_in_production = true #Note DO NOT USE THIS IN PRODUCTION!!!!

    [nss]
    filter_users = root
    filter_groups = root

    # override the user home directory that is provided by the LDAP password entry
    override_homedir=/mnt/homes/%u

    # override the user shell that is provided by the LDAP password entry
    override_shell=/bin/bash
